# Generated by Django 5.1 on 2024-09-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
